# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nucleus < Formula
  desc "CLI for interfacing with Nucleus"
  homepage "https://usenucleus.cloud"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.3/nucleus_0.0.3_Darwin_arm64.tar.gz"
      sha256 "44f3ffcda5b1ed1ee48a9b78f932cb472e0edb7e32075892eaf4179cabc98089"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.3/nucleus_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "b2f2ecef6ee962221b27337f2c1c9077e1d05d6ba7b709f02df7a0e4e8e88745"

      def install
        bin.install "nucleus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.3/nucleus_0.0.3_Linux_x86_64.tar.gz"
      sha256 "7cdb56b6f34b8978d72088e02d76ed9f302c9d62777f6d63f4db34222882f99d"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.3/nucleus_0.0.3_Linux_arm64.tar.gz"
      sha256 "4a6979ee9b95a74216d5486197e7728d468db235174c9f376f721cae1b4541d5"

      def install
        bin.install "nucleus"
      end
    end
  end
end
