# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neosync < Formula
  desc "CLI for interfacing with Neosync"
  homepage "https://www.neosync.dev"
  version "0.4.52"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.52/neosync_0.4.52_darwin_amd64.tar.gz"
      sha256 "057f50c6ed41504af212a308a4813f6c36e1c117fcce26068346392dede7ae6e"

      def install
        bin.install "neosync"
      end
    end
    on_arm do
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.52/neosync_0.4.52_darwin_arm64.tar.gz"
      sha256 "51dd6855d7d0eeaa22a6d59a0a449c5f648ec5320e027746b0735d938db9dffb"

      def install
        bin.install "neosync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.52/neosync_0.4.52_linux_amd64.tar.gz"
        sha256 "30c5bd6c24acce2bd01f781e30c175c98f306e06379a3b73c64ce196ac9baec3"

        def install
          bin.install "neosync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.52/neosync_0.4.52_linux_arm64.tar.gz"
        sha256 "27ea1dd41ff40d6c35083a6c455c22b49fa8bb09dfa6cf186a58e834f6b55dc0"

        def install
          bin.install "neosync"
        end
      end
    end
  end
end
