# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neosync < Formula
  desc "CLI for interfacing with Neosync"
  homepage "https://www.neosync.dev"
  version "0.4.36"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.36/neosync_0.4.36_darwin_amd64.tar.gz"
      sha256 "fa231184eaaf922adf2c6ed6332f0406dbae6d9fdbe3e7f0c7f979cf7ebc0f8d"

      def install
        bin.install "neosync"
      end
    end
    on_arm do
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.36/neosync_0.4.36_darwin_arm64.tar.gz"
      sha256 "54411e671d9a974870ee5882a2bc2f282643d3556f6d57f571a1664cee3ccf50"

      def install
        bin.install "neosync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.36/neosync_0.4.36_linux_amd64.tar.gz"
        sha256 "1bed5f3eba01f50b6c5f339f359c1e23735e64237a6170d65604dd3c6e1e1e1a"

        def install
          bin.install "neosync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nucleuscloud/neosync/releases/download/v0.4.36/neosync_0.4.36_linux_arm64.tar.gz"
        sha256 "0ff66bcdb6fc5a6bdf1433c265bc381813e57e7fa02f2c7ce0251ef2377cdb1b"

        def install
          bin.install "neosync"
        end
      end
    end
  end
end
