# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neosync < Formula
  desc "CLI for interfacing with Neosync"
  homepage "https://neosync.dev"
  version "0.3.32"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.3.32/neosync_0.3.32_darwin_arm64.tar.gz"
      sha256 "4a8a08497dc3f62c955c5308f59846da90aae8c966d30881e8e5b3afd20c4158"

      def install
        bin.install "neosync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.3.32/neosync_0.3.32_darwin_amd64.tar.gz"
      sha256 "eee4ae57ec5f3619a4fdf275e1ac72682df51e51159b9af0727b7584019f403c"

      def install
        bin.install "neosync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.3.32/neosync_0.3.32_linux_arm64.tar.gz"
      sha256 "03f1391c04d5f09d8fca9f932544c96748d052e7c0df9353beae13f861ae6efa"

      def install
        bin.install "neosync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/neosync/releases/download/v0.3.32/neosync_0.3.32_linux_amd64.tar.gz"
      sha256 "8004ad056743883661231cc39a0fc0a2a34ee8c2df31b5993813ab3b8665e209"

      def install
        bin.install "neosync"
      end
    end
  end
end
