# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nucleus < Formula
  desc "CLI for interfacing with Nucleus"
  homepage "https://nucleuscloud.com"
  version "0.0.38"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.38/nucleus_0.0.38_darwin_arm64.tar.gz"
      sha256 "a4c5ec13b7762c9142b82b7a827b0903cd8a1c3eeb96c0fab12f7ebd0d521441"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.38/nucleus_0.0.38_darwin_amd64.tar.gz"
      sha256 "e262344cf18f0a5fb3a1757ff24ef5907cb75cd5a116844b9d413616ff6091e4"

      def install
        bin.install "nucleus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.38/nucleus_0.0.38_linux_arm64.tar.gz"
      sha256 "36343939ece0fc435dbef27d0647826497c85216572155a04a54d58f756d3935"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.0.38/nucleus_0.0.38_linux_amd64.tar.gz"
      sha256 "18b432a7106152218c2989ddd075e07970f75829aa49e569b5c8ebb653e8dfaf"

      def install
        bin.install "nucleus"
      end
    end
  end
end
