# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nucleus < Formula
  desc "CLI for interfacing with Nucleus"
  homepage "https://nucleuscloud.com"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.2.1/nucleus_0.2.1_darwin_amd64.tar.gz"
      sha256 "2accd2d98859a734c4477a5a73160e411e4cd7087984afb3dfa17e8f6c6b5892"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.2.1/nucleus_0.2.1_darwin_arm64.tar.gz"
      sha256 "1035105489ddaaa59c81def78f164b98c143ef143dff48012c015a1a9fa3fdf2"

      def install
        bin.install "nucleus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.2.1/nucleus_0.2.1_linux_arm64.tar.gz"
      sha256 "a7420d1d5fcf3983c25c54f0ea62177a6efa365e15be1ad9b65bb44f57aaaf11"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.2.1/nucleus_0.2.1_linux_amd64.tar.gz"
      sha256 "95ed0ce8ba153aef78cd07456afb188a16101601c6d5d93203fc8ef85a1b3fa1"

      def install
        bin.install "nucleus"
      end
    end
  end
end
