# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nucleus < Formula
  desc "CLI for interfacing with Nucleus"
  homepage "https://nucleuscloud.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.1.0/nucleus_0.1.0_darwin_arm64.tar.gz"
      sha256 "1e9973875edcee5e860bc3b9c88ef440195eb64fb2b42b8c9372ff2ef5dfcb94"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.1.0/nucleus_0.1.0_darwin_amd64.tar.gz"
      sha256 "227f10be4e8dd96ace9c06086e252aaa64dd561340f89abf2516a360420c4ec8"

      def install
        bin.install "nucleus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.1.0/nucleus_0.1.0_linux_amd64.tar.gz"
      sha256 "9cbfe27eff7a6b61d1a7fa896a93e3db2447c63707f8f4829ab82527bd57926a"

      def install
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nucleuscloud/cli/releases/download/v0.1.0/nucleus_0.1.0_linux_arm64.tar.gz"
      sha256 "0b81a89918ff9ad2b267a8c4c56c3985066f83441b42151431a02b6667b44ddc"

      def install
        bin.install "nucleus"
      end
    end
  end
end
