# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seacrypt < Formula
  desc "CLI and Library for decrypting secrets via AWS KMS"
  homepage "https://usenucleus.cloud"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.4/seacrypt_0.0.4_darwin_arm64.tar.gz"
      sha256 "c107d88119f1b17ee9085d890281b49e3b9e0fbf457e31e9e9a857f4511bc8c4"

      def install
        bin.install "seacrypt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.4/seacrypt_0.0.4_darwin_amd64.tar.gz"
      sha256 "63803a28b4bd1eb70f4e01a271d6953262c1db052702538d0718a40fa36b79f2"

      def install
        bin.install "seacrypt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.4/seacrypt_0.0.4_linux_arm64.tar.gz"
      sha256 "e0c032a68900b36f1825b5ca8a846d65d9d3027a84618780d02d99b8149f9a80"

      def install
        bin.install "seacrypt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.4/seacrypt_0.0.4_linux_amd64.tar.gz"
      sha256 "d0ffcf3c913258c089be5614eb82ab03939cad3f3b157f3e87d6845875f50cae"

      def install
        bin.install "seacrypt"
      end
    end
  end
end
