# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seacrypt < Formula
  desc "CLI and Library for decrypting secrets via AWS KMS"
  homepage "https://usenucleus.cloud"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.3/seacrypt_0.0.3_darwin_amd64.tar.gz"
      sha256 "37757dce5e6408afee906a17b2224bfa7cb5edfe38e5394bfb3a25be64af9302"

      def install
        bin.install "seacrypt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.3/seacrypt_0.0.3_darwin_arm64.tar.gz"
      sha256 "b91286c3906d357b8a722431ae8151aec9ffcb8944b94683e604bf25270a29dd"

      def install
        bin.install "seacrypt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.3/seacrypt_0.0.3_linux_arm64.tar.gz"
      sha256 "62f029e2c7c8c52bfcfaa1cf23e01ee0f5532d59cf5d580cbb384ebad762e699"

      def install
        bin.install "seacrypt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nucleuscloud/seacrypt/releases/download/v0.0.3/seacrypt_0.0.3_linux_amd64.tar.gz"
      sha256 "ea6dbc91aaa1355c4a35cb949bd38418c42ddd47a01345813aa099a3efa60cb6"

      def install
        bin.install "seacrypt"
      end
    end
  end
end
